import { faBuilding, faMapMarkerAlt, faClock } from "@fortawesome/free-solid-svg-icons";

export const internshipData = [
  {
    id: 1,
    title: "Electrical Engineering Intern",
    type: "Full-time",
    company: "PowerGrid Ethiopia",
    companyIcon: faBuilding,
    description: "Support electrical system design and maintenance in power distribution projects.",
    location: "Bahir Dar, Ethiopia",
    locationIcon: faMapMarkerAlt,
    duration: "6 months",
    durationIcon: faClock,
    skills: ["AutoCAD", "Circuit Design", "Power Systems"],
    applyLink: "#"
  },
  {
    id: 2,
    title: "Mechanical Design Intern",
    type: "Full-time",
    company: "Manufacturing Pro",
    companyIcon: faBuilding,
    description: "Assist in mechanical design processes and work with CAD software on real projects.",
    location: "Bahir Dar, Ethiopia",
    locationIcon: faMapMarkerAlt,
    duration: "4 months",
    durationIcon: faClock,
    skills: ["SolidWorks", "CAD", "3D Modeling"],
    applyLink: "#"
  },
  {
    id: 3,
    title: "Business Analyst Intern",
    type: "Part-time",
    company: "Consulting Partners",
    companyIcon: faBuilding,
    description: "Conduct market research and support strategic business planning initiatives.",
    location: "Remote",
    locationIcon: faMapMarkerAlt,
    duration: "3 months",
    durationIcon: faClock,
    skills: ["Excel", "Market Research", "Presentation"],
    applyLink: "#"
  },
  {
    id: 4,
    title: "Software Development Intern",
    type: "Full-time",
    company: "Tech Solutions Ethiopia",
    companyIcon: faBuilding,
    description: "Develop web and mobile applications using modern frameworks and technologies.",
    location: "Addis Ababa, Ethiopia",
    locationIcon: faMapMarkerAlt,
    duration: "6 months",
    durationIcon: faClock,
    skills: ["React", "Node.js", "Python"],
    applyLink: "#"
  },
  {
    id: 5,
    title: "Civil Engineering Intern",
    type: "Full-time",
    company: "BuildRight Construction",
    companyIcon: faBuilding,
    description: "Participate in construction project planning and site supervision activities.",
    location: "Bahir Dar, Ethiopia",
    locationIcon: faMapMarkerAlt,
    duration: "6 months",
    durationIcon: faClock,
    skills: ["AutoCAD", "Project Management", "Structural Analysis"],
    applyLink: "#"
  },
  {
    id: 6,
    title: "Marketing Intern",
    type: "Part-time",
    company: "Digital Marketing Agency",
    companyIcon: faBuilding,
    description: "Create content strategies and manage social media campaigns for clients.",
    location: "Remote",
    locationIcon: faMapMarkerAlt,
    duration: "3 months",
    durationIcon: faClock,
    skills: ["Social Media", "Content Creation", "SEO"],
    applyLink: "#"
  },
  {
    id: 7,
    title: "Software Development Intern",
    type: "Full-time",
    company: "Tech Solutions Ethiopia",
    companyIcon: faBuilding,
    description: "Develop web and mobile applications using modern frameworks and technologies.",
    location: "Addis Ababa, Ethiopia",
    locationIcon: faMapMarkerAlt,
    duration: "6 months",
    durationIcon: faClock,
    skills: ["React", "Node.js", "Python"],
    applyLink: "#"
  },
  {
    id: 8,
    title: "Civil Engineering Intern",
    type: "Full-time",
    company: "BuildRight Construction",
    companyIcon: faBuilding,
    description: "Participate in construction project planning and site supervision activities.",
    location: "Bahir Dar, Ethiopia",
    locationIcon: faMapMarkerAlt,
    duration: "6 months",
    durationIcon: faClock,
    skills: ["AutoCAD", "Project Management", "Structural Analysis"],
    applyLink: "#"
  },
  {
    id: 9,
    title: "Marketing Intern",
    type: "Part-time",
    company: "Digital Marketing Agency",
    companyIcon: faBuilding,
    description: "Create content strategies and manage social media campaigns for clients.",
    location: "Remote",
    locationIcon: faMapMarkerAlt,
    duration: "3 months",
    durationIcon: faClock,
    skills: ["Social Media", "Content Creation", "SEO"],
    applyLink: "#"
  }
];